export const ADMIN_SIGNIN_REQ = "ADMIN_SIGNIN_REQ"
export const ADMIN_SIGNIN_SUCCESS = "ADMIN_SIGNIN_SUCCESS"
export const ADMIN_SIGNIN_FAIL = "ADMIN_SIGNIN_FAIL"

export const ADMIN_GOOGLE_SIGNIN_REQ = "ADMIN_GOOGLE_SIGNIN_REQ"
export const ADMIN_GOOGLE_SIGNIN_SUCCESS = "ADMIN_GOOGLE_SIGNIN_SUCCESS"
export const ADMIN_GOOGLE_SIGNUP_SUCCESS = "ADMIN_GOOGLE_SIGNUP_SUCCESS"
export const ADMIN_GOOGLE_SIGNIN_FAIL = "ADMIN_GOOGLE_SIGNIN_FAIL"


export const ADMIN_LOGOUT_REQ = "ADMIN_LOGOUT_REQ"
export const ADMIN_LOGOUT_SUCCESS = "ADMIN_LOGOUT_SUCCESS"
export const ADMIN_LOGOUT_FAIL = "ADMIN_LOGOUT_FAIL"

//MIDDLEWARE
export const LOGGED_OUT_MIDDLEWARE_REQ = "LOGGED_OUT_MIDDLEWARE_REQ"
export const LOGGED_OUT_MIDDLEWARE_SUCCESS = "LOGGED_OUT_MIDDLEWARE_SUCCESS"
export const LOGGED_OUT_MIDDLEWARE_FAIL = "LOGGED_OUT_MIDDLEWARE_FAIL"

export const LOGGED_IN_MIDDLEWARE_REQ = "LOGGED_IN_MIDDLEWARE_REQ"
export const LOGGED_IN_MIDDLEWARE_SUCCESS = "LOGGED_IN_MIDDLEWARE_SUCCESS"
export const LOGGED_IN_MIDDLEWARE_FAIL = "LOGGED_IN_MIDDLEWARE_FAIL"