export const GET_BARBERLIST_REQ = "GET_BARBERLIST_REQ"
export const GET_BARBERLIST_SUCCESS = "GET_BARBERLIST_SUCCESS"
export const GET_BARBERLIST_FAIL = "GET_BARBERLIST_FAIL"

export const GET_BARBER_SERVICES_REQ = "GET_BARBER_SERVICES_REQ"
export const GET_BARBER_SERVICES_SUCCESS = "GET_BARBER_SERVICES_SUCCESS"
export const GET_BARBER_SERVICES_FAIL = "GET_BARBER_SERVICES_FAIL"

export const GET_ALL_SALON_SERVICES_REQ = "GET_ALL_SALON_SERVICES_REQ"
export const GET_ALL_SALON_SERVICES_SUCCESS = "GET_ALL_SALON_SERVICES_SUCCESS"
export const GET_ALL_SALON_SERVICES_FAIL = "GET_ALL_SALON_SERVICES_FAIL"

export const GET_BARBERS_BY_MULTIPLE_SERVICES_REQ = "GET_BARBERS_BY_MULTIPLE_SERVICES_REQ"
export const GET_BARBERS_BY_MULTIPLE_SERVICES_SUCCESS = "GET_BARBERS_BY_MULTIPLE_SERVICES_SUCCESS"
export const GET_BARBERS_BY_MULTIPLE_SERVICES_FAIL = "GET_BARBERS_BY_MULTIPLE_SERVICES_FAIL"