export const QUELIST_REQ = "QUELIST_REQ"
export const QUELIST_SUCCESS = "QUELIST_SUCCESS"
export const QUELIST_FAIL = "QUELIST_FAIL"

export const SINGLE_JOINQUEUE_REQ = "SINGLE_JOINQUEUE_REQ"
export const SINGLE_JOINQUEUE_SUCCESS = "SINGLE_JOINQUEUE_SUCCESS"
export const SINGLE_JOINQUEUE_FAIL = "SINGLE_JOINQUEUE_FAIL"

export const CUSTOMER_API_REQ = "CUSTOMER_API_REQ"
export const CUSTOMER_API_SUCCESS = "CUSTOMER_API_SUCCESS"
export const CUSTOMER_API_FAIL = "CUSTOMER_API_FAIL"

export const AUTOJOIN_REQ = "AUTOJOIN_REQ"
export const AUTOJOIN_SUCCESS = "AUTOJOIN_SUCCESS"
export const AUTOJOIN_FAIL = "AUTOJOIN_FAIL"

export const AUTO_GETALL_SALON_SERVICES_REQ = "AUTO_GETALL_SALON_SERVICES_REQ"
export const AUTO_GETALL_SALON_SERVICES_SUCCESS = "AUTO_GETALL_SALON_SERVICES_SUCCESS"
export const AUTO_GETALL_SALON_SERVICES_FAIL = "AUTO_GETALL_SALON_SERVICES_FAIL"