export const QUELIST_REQ = "QUELIST_REQ"
export const QUELIST_SUCCESS = "QUELIST_SUCCESS"
export const QUELIST_FAIL = "QUELIST_FAIL"

export const SINGLE_JOINQUEUE_REQ = "SINGLE_JOINQUEUE_REQ"
export const SINGLE_JOINQUEUE_SUCCESS = "SINGLE_JOINQUEUE_SUCCESS"
export const SINGLE_JOINQUEUE_FAIL = "SINGLE_JOINQUEUE_FAIL"